# Setup
title: KirvilNET Docs
tagline: Documentation for all KirvilNET projects
url: https://docs.kirvilnet..com
paginate: 3
baseurl: ""
permalink: pretty

theme: just-the-docs

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Avic Ndugu
  url: https://https://twitter.com/_ndugu
  email: avicndugu1234@gmail.com

# Custom vars
version: 3.0.0

#Just the docs
color_scheme: dark
nav_enabled: true
