# Setup
title: KirvilNET Docs
tagline: Documentation for all KirvilNET projects
url: https://docs.kirvilnet..com
paginate: 3
baseurl: ""
permalink: pretty

theme: just-the-docs

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Custom vars
version: 3.0.0

#Just the docs
color_scheme: dark
nav_enabled: true

aux_links:
  "KirvilNET on GitHub":
    - "https://github.com/KirvilNET/"
    
aux_links_new_tab: false

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
  tip:
    title: Tip
    color: green
  highlight:
    title: Highlight
    color: yellow
  important:
    title: Important
    color: blue